"""Ground-truth provenance: hash the physics that produced a GT directory.

Lives in ``utils/`` (not ``data_generation/``) so that BOTH the generator and the
dataloaders can import it without the loaders depending on the generation package. The
check must never be able to silently no-op — a stale-GT guard that can be skipped is not a
guard.

THE FAILURE THIS PREVENTS
------------------------
The active config is ``nyu_train_mode: "subset"`` + ``nyu_test_mode: "tail"``.
``generate_gt_nyu_subset.py`` writes GT only for indices in the filtered TRAINING pool
(``filter_nyu_subset`` restricts to ``[0, split_idx)``), but ``data/nyu.get_test_loader``
builds the test set from ``range(split_idx, N)`` and loads GT for exactly those tail
indices.

So on a pre-existing GT directory the ~2000 tail files SURVIVE FROM THE PREVIOUS PHYSICS.
You train on new-physics GT and are scored against old-physics GT — silently, with no
missing file, no error, and ``count_files.py`` reporting the directory as healthy. There
was previously no manifest, hash, or provenance of any kind in the repo.

The generator writes ``physics_manifest.json`` into the GT dir; the loader asserts the live
config still hashes to the same value.
"""

import hashlib
import json
import os

# Every config key that changes the value of a GT pixel. If you add a physics knob, add it
# here, or a change to it will not invalidate existing ground truth.
PHYSICS_KEYS = (
    'jerlov_water_types', 'gamma_angular', 'alpha_metric', 'complex_model',
    'complex_depth_mode', 'complex_beta', 'complex_beta_scale',
    'nyu_water_clarity', 'make3d_water_clarity', 'kitti_water_clarity',
    'nyu_focal_px', 'make3d_focal_px', 'kitti_focal_px',
    'nyu_max_depth_m', 'make3d_max_depth_m', 'kitti_max_depth_m',
    'u', 'turbu_c', 'turbu_pr', 'turbu_sigma', 'depth_levels',
    'airlight_bg_depth', 'nyu_airlight_brightness_min', 'make3d_airlight_brightness_min',
    'random_seed',
)

MANIFEST_NAME = 'physics_manifest.json'


def physics_fingerprint(cfg):
    """(payload, 16-hex-char hash) of every config key that changes a GT pixel."""
    from utils.depth_range import DEPTH_CLIP_FRAC

    payload = {}
    for k in PHYSICS_KEYS:
        v = getattr(cfg, k, None)
        if isinstance(v, (list, tuple)):
            v = [list(x) if isinstance(x, (list, tuple)) else x for x in v]
        payload[k] = v
    payload['depth_clip_frac'] = DEPTH_CLIP_FRAC
    # The RESAMPLING used for the depth map changes every GT pixel at an object boundary, so it
    # is part of the physics. It was NOT here originally, and that omission let a
    # generator(BICUBIC)/loader(NEAREST) mismatch pass provenance silently.
    payload['depth_resample'] = 'nearest'
    payload['image_resample'] = 'bicubic'
    blob = json.dumps(payload, sort_keys=True, default=str)
    return payload, hashlib.sha256(blob.encode('utf-8')).hexdigest()[:16]


def write_physics_manifest(gt_dir, cfg, covered_indices=None):
    """Record, in ``gt_dir``, the physics that produced the ground truth there.

    ``covered_indices``: which indices this generation run actually WROTE. Without it the
    manifest is directory-level while staleness is per-index, and a subset-only regen stamps a
    fresh manifest over a directory whose test-tail files are still the old physics (see
    check_physics_manifest). Indices are UNIONed with whatever the existing manifest recorded,
    so generating the subset and the tail in separate runs still ends up with full coverage --
    but ONLY if the physics hash is unchanged; a hash change resets coverage, because every
    pre-existing file is now stale by definition.
    """
    payload, digest = physics_fingerprint(cfg)
    os.makedirs(gt_dir, exist_ok=True)
    path = os.path.join(gt_dir, MANIFEST_NAME)

    covered = set()
    if os.path.exists(path):
        try:
            with open(path) as fh:
                prev = json.load(fh)
            if prev.get('physics_hash') == digest:
                covered = set(int(i) for i in (prev.get('covered_indices') or []))
        except Exception:
            covered = set()
    if covered_indices is not None:
        covered |= set(int(i) for i in covered_indices)

    with open(path, 'w') as fh:
        json.dump({'physics_hash': digest,
                   'covered_indices': sorted(covered),
                   'params': payload},
                  fh, indent=2, sort_keys=True, default=str)
    print('[gt] physics_hash=%s  covered=%d indices -> %s' % (digest, len(covered), path))
    return digest


def check_physics_manifest(gt_dir, cfg, required_indices=None):
    """Assert the GT in ``gt_dir`` was generated by the physics this config describes.

    ``required_indices``: the indices the caller is about to LOAD. This is not optional
    paranoia — without it the guard is a LIE, and here is exactly why:

    The manifest is DIRECTORY-level but staleness is PER-INDEX. A subset-only regeneration
    (``generate_gt_nyu_subset.py`` without ``--with-test-tail``) rewrites GT for the training
    indices and stamps a FRESH manifest into the directory — while the ~2000 test-TAIL files
    sitting in the same directory are still the OLD physics. A hash check then compares
    fresh-against-fresh, reports "GT matches config", and you train on new-physics GT and are
    scored against old-physics GT. Silently. Which is precisely the failure the manifest was
    introduced to prevent.

    So the manifest also records WHICH indices it covers, and the loader asserts the indices
    it needs are in that set.

    Warn (do not fail) if the manifest is absent — an older GT directory predates this check.
    HARD FAIL on a hash mismatch or on missing coverage.
    """
    _, live = physics_fingerprint(cfg)
    path = os.path.join(gt_dir, MANIFEST_NAME)

    if not os.path.exists(path):
        print("[provenance] WARNING: no %s in %s — cannot verify this GT was generated with "
              "the current physics (live hash %s). If you changed any physics parameter, the "
              "GT is STALE: rerun scripts/regenerate_nyu_gt.sh."
              % (MANIFEST_NAME, gt_dir, live))
        return None

    with open(path) as fh:
        blob = json.load(fh)
    disk = blob.get('physics_hash')

    if disk != live:
        raise RuntimeError(
            "\n*** PHYSICS MISMATCH — REFUSING TO RUN ***\n"
            "  GT directory : %s\n"
            "  GT was generated with physics_hash = %s\n"
            "  live config hashes to              = %s\n"
            "\n"
            "The ground truth on disk does NOT match the configured physics, so every number\n"
            "you would produce is meaningless. Regenerate it (params -> filter -> GT, and the\n"
            "TEST TAIL too):\n"
            "      scripts/regenerate_nyu_gt.sh\n"
            "or restore the previous physics parameters in config.yaml.\n"
            % (gt_dir, disk, live))

    covered = blob.get('covered_indices')
    if required_indices is not None and covered is not None:
        missing = sorted(set(int(i) for i in required_indices) - set(int(i) for i in covered))
        if missing:
            raise RuntimeError(
                "\n*** STALE GROUND TRUTH — REFUSING TO RUN ***\n"
                "  GT directory : %s\n"
                "  The physics hash matches, but %d of the %d indices this loader needs were\n"
                "  NOT written by that generation run. Their .npy files on disk are LEFT OVER\n"
                "  FROM THE PREVIOUS PHYSICS.\n"
                "  first missing indices: %s%s\n"
                "\n"
                "  This is the classic subset/tail split: the subset generator writes GT only\n"
                "  for the TRAINING indices, but the test loader reads the TAIL. Fix:\n"
                "      python data_generation/generate_gt_nyu_subset.py --with-test-tail\n"
                "  (scripts/regenerate_nyu_gt.sh already passes that flag).\n"
                % (gt_dir, len(missing), len(required_indices),
                   missing[:10], ' ...' if len(missing) > 10 else ''))

    n_cov = len(covered) if covered is not None else -1
    print('[provenance] physics_hash=%s (GT matches config, %s indices covered)'
          % (live, n_cov if n_cov >= 0 else 'coverage not recorded'))
    return live
