"""Ground-truth provenance: hash the physics that produced a GT directory.

Lives in ``utils/`` (not ``data_generation/``) so that BOTH the generator and the
dataloaders can import it without the loaders depending on the generation package. The
check must never be able to silently no-op — a stale-GT guard that can be skipped is not a
guard.

THE FAILURE THIS PREVENTS
------------------------
The active config is ``nyu_train_mode: "subset"`` + ``nyu_test_mode: "tail"``.
``generate_gt_nyu_subset.py`` writes GT only for indices in the filtered TRAINING pool
(``filter_nyu_subset`` restricts to ``[0, split_idx)``), but ``data/nyu.get_test_loader``
builds the test set from ``range(split_idx, N)`` and loads GT for exactly those tail
indices.

So on a pre-existing GT directory the ~2000 tail files SURVIVE FROM THE PREVIOUS PHYSICS.
You train on new-physics GT and are scored against old-physics GT — silently, with no
missing file, no error, and ``count_files.py`` reporting the directory as healthy. There
was previously no manifest, hash, or provenance of any kind in the repo.

The generator writes ``physics_manifest.json`` into the GT dir; the loader asserts the live
config still hashes to the same value.
"""

import hashlib
import json
import os

# Every config key that changes the value of a GT pixel. If you add a physics knob, add it
# here, or a change to it will not invalidate existing ground truth.
PHYSICS_KEYS = (
    'jerlov_water_types', 'gamma_angular', 'alpha_metric', 'complex_model',
    'complex_depth_mode', 'complex_beta', 'complex_beta_scale',
    'nyu_water_clarity', 'make3d_water_clarity', 'kitti_water_clarity',
    'nyu_focal_px', 'make3d_focal_px', 'kitti_focal_px',
    'nyu_max_depth_m', 'make3d_max_depth_m', 'kitti_max_depth_m',
    'u', 'turbu_c', 'turbu_pr', 'turbu_sigma', 'depth_levels',
    'airlight_bg_depth', 'nyu_airlight_brightness_min', 'make3d_airlight_brightness_min',
    'random_seed',
)

MANIFEST_NAME = 'physics_manifest.json'


def physics_fingerprint(cfg):
    """(payload, 16-hex-char hash) of every config key that changes a GT pixel."""
    from utils.depth_range import DEPTH_CLIP_FRAC

    payload = {}
    for k in PHYSICS_KEYS:
        v = getattr(cfg, k, None)
        if isinstance(v, (list, tuple)):
            v = [list(x) if isinstance(x, (list, tuple)) else x for x in v]
        payload[k] = v
    payload['depth_clip_frac'] = DEPTH_CLIP_FRAC
    blob = json.dumps(payload, sort_keys=True, default=str)
    return payload, hashlib.sha256(blob.encode('utf-8')).hexdigest()[:16]


def write_physics_manifest(gt_dir, cfg):
    """Record, in ``gt_dir``, the physics that produced the ground truth there."""
    payload, digest = physics_fingerprint(cfg)
    os.makedirs(gt_dir, exist_ok=True)
    path = os.path.join(gt_dir, MANIFEST_NAME)
    with open(path, 'w') as fh:
        json.dump({'physics_hash': digest, 'params': payload}, fh,
                  indent=2, sort_keys=True, default=str)
    print('[gt] physics_hash=%s -> %s' % (digest, path))
    return digest


def check_physics_manifest(gt_dir, cfg):
    """Assert the GT in ``gt_dir`` was generated by the physics this config describes.

    Warn (do not fail) if the manifest is absent — an older GT directory predates this
    check and we cannot know either way. HARD FAIL if it is present and disagrees, because
    that is a definite train/test physics split.
    """
    _, live = physics_fingerprint(cfg)
    path = os.path.join(gt_dir, MANIFEST_NAME)

    if not os.path.exists(path):
        print("[provenance] WARNING: no %s in %s — cannot verify this GT was generated with "
              "the current physics (live hash %s). If you changed any physics parameter, the "
              "GT is STALE: rerun scripts/regenerate_nyu_gt.sh."
              % (MANIFEST_NAME, gt_dir, live))
        return None

    with open(path) as fh:
        disk = json.load(fh).get('physics_hash')

    if disk != live:
        raise RuntimeError(
            "\n*** PHYSICS MISMATCH — REFUSING TO RUN ***\n"
            "  GT directory : %s\n"
            "  GT was generated with physics_hash = %s\n"
            "  live config hashes to              = %s\n"
            "\n"
            "The ground truth on disk does NOT match the configured physics, so every number\n"
            "you would produce is meaningless. Regenerate it (params -> filter -> GT, and the\n"
            "TEST TAIL too):\n"
            "      scripts/regenerate_nyu_gt.sh\n"
            "or restore the previous physics parameters in config.yaml.\n"
            % (gt_dir, disk, live))

    print('[provenance] physics_hash=%s (GT matches config)' % live)
    return live
